-- Seed: TablaDistritosLima — complete 20×20 district time matrix
-- Values from docs/programador-ia/06-district-time-matrix.md
-- PostgreSQL syntax

INSERT INTO "TablaDistritosLima" (distrito_origen, distrito_destino, tiempo_min) VALUES
  ('Cercado de Lima', 'Cercado de Lima', 0),   ('Cercado de Lima', 'Breña', 20),   ('Cercado de Lima', 'La Victoria', 25),   ('Cercado de Lima', 'Lince', 30),   ('Cercado de Lima', 'San Isidro', 40),
  ('Cercado de Lima', 'Miraflores', 50),   ('Cercado de Lima', 'San Borja', 45),   ('Cercado de Lima', 'Surquillo', 45),   ('Cercado de Lima', 'Barranco', 60),   ('Cercado de Lima', 'Surco', 65),
  ('Cercado de Lima', 'La Molina', 80),   ('Cercado de Lima', 'Chorrillos', 70),   ('Cercado de Lima', 'Los Olivos', 75),   ('Cercado de Lima', 'San Martín de Porres', 65),   ('Cercado de Lima', 'Independencia', 55),
  ('Cercado de Lima', 'San Miguel', 50),   ('Cercado de Lima', 'Magdalena del Mar', 45),   ('Cercado de Lima', 'Pueblo Libre', 40),   ('Cercado de Lima', 'Callao', 60),   ('Cercado de Lima', 'Ate', 65),
  ('Breña', 'Cercado de Lima', 20),   ('Breña', 'Breña', 0),   ('Breña', 'La Victoria', 30),   ('Breña', 'Lince', 30),   ('Breña', 'San Isidro', 40),
  ('Breña', 'Miraflores', 50),   ('Breña', 'San Borja', 45),   ('Breña', 'Surquillo', 45),   ('Breña', 'Barranco', 60),   ('Breña', 'Surco', 65),
  ('Breña', 'La Molina', 85),   ('Breña', 'Chorrillos', 70),   ('Breña', 'Los Olivos', 65),   ('Breña', 'San Martín de Porres', 55),   ('Breña', 'Independencia', 50),
  ('Breña', 'San Miguel', 40),   ('Breña', 'Magdalena del Mar', 35),   ('Breña', 'Pueblo Libre', 30),   ('Breña', 'Callao', 50),   ('Breña', 'Ate', 70),
  ('La Victoria', 'Cercado de Lima', 25),   ('La Victoria', 'Breña', 30),   ('La Victoria', 'La Victoria', 0),   ('La Victoria', 'Lince', 25),   ('La Victoria', 'San Isidro', 35),
  ('La Victoria', 'Miraflores', 40),   ('La Victoria', 'San Borja', 35),   ('La Victoria', 'Surquillo', 35),   ('La Victoria', 'Barranco', 55),   ('La Victoria', 'Surco', 60),
  ('La Victoria', 'La Molina', 70),   ('La Victoria', 'Chorrillos', 65),   ('La Victoria', 'Los Olivos', 80),   ('La Victoria', 'San Martín de Porres', 70),   ('La Victoria', 'Independencia', 65),
  ('La Victoria', 'San Miguel', 60),   ('La Victoria', 'Magdalena del Mar', 55),   ('La Victoria', 'Pueblo Libre', 50),   ('La Victoria', 'Callao', 70),   ('La Victoria', 'Ate', 50),
  ('Lince', 'Cercado de Lima', 30),   ('Lince', 'Breña', 30),   ('Lince', 'La Victoria', 25),   ('Lince', 'Lince', 0),   ('Lince', 'San Isidro', 20),
  ('Lince', 'Miraflores', 30),   ('Lince', 'San Borja', 25),   ('Lince', 'Surquillo', 25),   ('Lince', 'Barranco', 50),   ('Lince', 'Surco', 55),
  ('Lince', 'La Molina', 70),   ('Lince', 'Chorrillos', 60),   ('Lince', 'Los Olivos', 75),   ('Lince', 'San Martín de Porres', 65),   ('Lince', 'Independencia', 65),
  ('Lince', 'San Miguel', 50),   ('Lince', 'Magdalena del Mar', 45),   ('Lince', 'Pueblo Libre', 40),   ('Lince', 'Callao', 65),   ('Lince', 'Ate', 60),
  ('San Isidro', 'Cercado de Lima', 40),   ('San Isidro', 'Breña', 40),   ('San Isidro', 'La Victoria', 35),   ('San Isidro', 'Lince', 20),   ('San Isidro', 'San Isidro', 0),
  ('San Isidro', 'Miraflores', 20),   ('San Isidro', 'San Borja', 20),   ('San Isidro', 'Surquillo', 25),   ('San Isidro', 'Barranco', 40),   ('San Isidro', 'Surco', 45),
  ('San Isidro', 'La Molina', 65),   ('San Isidro', 'Chorrillos', 55),   ('San Isidro', 'Los Olivos', 80),   ('San Isidro', 'San Martín de Porres', 70),   ('San Isidro', 'Independencia', 75),
  ('San Isidro', 'San Miguel', 40),   ('San Isidro', 'Magdalena del Mar', 35),   ('San Isidro', 'Pueblo Libre', 35),   ('San Isidro', 'Callao', 60),   ('San Isidro', 'Ate', 70),
  ('Miraflores', 'Cercado de Lima', 50),   ('Miraflores', 'Breña', 50),   ('Miraflores', 'La Victoria', 40),   ('Miraflores', 'Lince', 30),   ('Miraflores', 'San Isidro', 20),
  ('Miraflores', 'Miraflores', 0),   ('Miraflores', 'San Borja', 20),   ('Miraflores', 'Surquillo', 15),   ('Miraflores', 'Barranco', 25),   ('Miraflores', 'Surco', 35),
  ('Miraflores', 'La Molina', 55),   ('Miraflores', 'Chorrillos', 40),   ('Miraflores', 'Los Olivos', 90),   ('Miraflores', 'San Martín de Porres', 80),   ('Miraflores', 'Independencia', 85),
  ('Miraflores', 'San Miguel', 45),   ('Miraflores', 'Magdalena del Mar', 40),   ('Miraflores', 'Pueblo Libre', 40),   ('Miraflores', 'Callao', 70),   ('Miraflores', 'Ate', 75),
  ('San Borja', 'Cercado de Lima', 45),   ('San Borja', 'Breña', 45),   ('San Borja', 'La Victoria', 35),   ('San Borja', 'Lince', 25),   ('San Borja', 'San Isidro', 20),
  ('San Borja', 'Miraflores', 20),   ('San Borja', 'San Borja', 0),   ('San Borja', 'Surquillo', 20),   ('San Borja', 'Barranco', 35),   ('San Borja', 'Surco', 30),
  ('San Borja', 'La Molina', 50),   ('San Borja', 'Chorrillos', 45),   ('San Borja', 'Los Olivos', 85),   ('San Borja', 'San Martín de Porres', 75),   ('San Borja', 'Independencia', 80),
  ('San Borja', 'San Miguel', 55),   ('San Borja', 'Magdalena del Mar', 50),   ('San Borja', 'Pueblo Libre', 45),   ('San Borja', 'Callao', 75),   ('San Borja', 'Ate', 60),
  ('Surquillo', 'Cercado de Lima', 45),   ('Surquillo', 'Breña', 45),   ('Surquillo', 'La Victoria', 35),   ('Surquillo', 'Lince', 25),   ('Surquillo', 'San Isidro', 25),
  ('Surquillo', 'Miraflores', 15),   ('Surquillo', 'San Borja', 20),   ('Surquillo', 'Surquillo', 0),   ('Surquillo', 'Barranco', 20),   ('Surquillo', 'Surco', 30),
  ('Surquillo', 'La Molina', 55),   ('Surquillo', 'Chorrillos', 35),   ('Surquillo', 'Los Olivos', 90),   ('Surquillo', 'San Martín de Porres', 80),   ('Surquillo', 'Independencia', 85),
  ('Surquillo', 'San Miguel', 50),   ('Surquillo', 'Magdalena del Mar', 45),   ('Surquillo', 'Pueblo Libre', 45),   ('Surquillo', 'Callao', 70),   ('Surquillo', 'Ate', 70),
  ('Barranco', 'Cercado de Lima', 60),   ('Barranco', 'Breña', 60),   ('Barranco', 'La Victoria', 55),   ('Barranco', 'Lince', 50),   ('Barranco', 'San Isidro', 40),
  ('Barranco', 'Miraflores', 25),   ('Barranco', 'San Borja', 35),   ('Barranco', 'Surquillo', 20),   ('Barranco', 'Barranco', 0),   ('Barranco', 'Surco', 25),
  ('Barranco', 'La Molina', 55),   ('Barranco', 'Chorrillos', 20),   ('Barranco', 'Los Olivos', 100),   ('Barranco', 'San Martín de Porres', 90),   ('Barranco', 'Independencia', 95),
  ('Barranco', 'San Miguel', 65),   ('Barranco', 'Magdalena del Mar', 60),   ('Barranco', 'Pueblo Libre', 60),   ('Barranco', 'Callao', 85),   ('Barranco', 'Ate', 80),
  ('Surco', 'Cercado de Lima', 65),   ('Surco', 'Breña', 65),   ('Surco', 'La Victoria', 60),   ('Surco', 'Lince', 55),   ('Surco', 'San Isidro', 45),
  ('Surco', 'Miraflores', 35),   ('Surco', 'San Borja', 30),   ('Surco', 'Surquillo', 30),   ('Surco', 'Barranco', 25),   ('Surco', 'Surco', 0),
  ('Surco', 'La Molina', 35),   ('Surco', 'Chorrillos', 30),   ('Surco', 'Los Olivos', 95),   ('Surco', 'San Martín de Porres', 85),   ('Surco', 'Independencia', 90),
  ('Surco', 'San Miguel', 65),   ('Surco', 'Magdalena del Mar', 60),   ('Surco', 'Pueblo Libre', 60),   ('Surco', 'Callao', 85),   ('Surco', 'Ate', 65),
  ('La Molina', 'Cercado de Lima', 80),   ('La Molina', 'Breña', 85),   ('La Molina', 'La Victoria', 70),   ('La Molina', 'Lince', 70),   ('La Molina', 'San Isidro', 65),
  ('La Molina', 'Miraflores', 55),   ('La Molina', 'San Borja', 50),   ('La Molina', 'Surquillo', 55),   ('La Molina', 'Barranco', 55),   ('La Molina', 'Surco', 35),
  ('La Molina', 'La Molina', 0),   ('La Molina', 'Chorrillos', 55),   ('La Molina', 'Los Olivos', 110),   ('La Molina', 'San Martín de Porres', 100),   ('La Molina', 'Independencia', 100),
  ('La Molina', 'San Miguel', 90),   ('La Molina', 'Magdalena del Mar', 85),   ('La Molina', 'Pueblo Libre', 85),   ('La Molina', 'Callao', 105),   ('La Molina', 'Ate', 45),
  ('Chorrillos', 'Cercado de Lima', 70),   ('Chorrillos', 'Breña', 70),   ('Chorrillos', 'La Victoria', 65),   ('Chorrillos', 'Lince', 60),   ('Chorrillos', 'San Isidro', 55),
  ('Chorrillos', 'Miraflores', 40),   ('Chorrillos', 'San Borja', 45),   ('Chorrillos', 'Surquillo', 35),   ('Chorrillos', 'Barranco', 20),   ('Chorrillos', 'Surco', 30),
  ('Chorrillos', 'La Molina', 55),   ('Chorrillos', 'Chorrillos', 0),   ('Chorrillos', 'Los Olivos', 100),   ('Chorrillos', 'San Martín de Porres', 90),   ('Chorrillos', 'Independencia', 95),
  ('Chorrillos', 'San Miguel', 70),   ('Chorrillos', 'Magdalena del Mar', 65),   ('Chorrillos', 'Pueblo Libre', 65),   ('Chorrillos', 'Callao', 90),   ('Chorrillos', 'Ate', 85),
  ('Los Olivos', 'Cercado de Lima', 75),   ('Los Olivos', 'Breña', 65),   ('Los Olivos', 'La Victoria', 80),   ('Los Olivos', 'Lince', 75),   ('Los Olivos', 'San Isidro', 80),
  ('Los Olivos', 'Miraflores', 90),   ('Los Olivos', 'San Borja', 85),   ('Los Olivos', 'Surquillo', 90),   ('Los Olivos', 'Barranco', 100),   ('Los Olivos', 'Surco', 95),
  ('Los Olivos', 'La Molina', 110),   ('Los Olivos', 'Chorrillos', 100),   ('Los Olivos', 'Los Olivos', 0),   ('Los Olivos', 'San Martín de Porres', 25),   ('Los Olivos', 'Independencia', 30),
  ('Los Olivos', 'San Miguel', 55),   ('Los Olivos', 'Magdalena del Mar', 60),   ('Los Olivos', 'Pueblo Libre', 60),   ('Los Olivos', 'Callao', 45),   ('Los Olivos', 'Ate', 95),
  ('San Martín de Porres', 'Cercado de Lima', 65),   ('San Martín de Porres', 'Breña', 55),   ('San Martín de Porres', 'La Victoria', 70),   ('San Martín de Porres', 'Lince', 65),   ('San Martín de Porres', 'San Isidro', 70),
  ('San Martín de Porres', 'Miraflores', 80),   ('San Martín de Porres', 'San Borja', 75),   ('San Martín de Porres', 'Surquillo', 80),   ('San Martín de Porres', 'Barranco', 90),   ('San Martín de Porres', 'Surco', 85),
  ('San Martín de Porres', 'La Molina', 100),   ('San Martín de Porres', 'Chorrillos', 90),   ('San Martín de Porres', 'Los Olivos', 25),   ('San Martín de Porres', 'San Martín de Porres', 0),   ('San Martín de Porres', 'Independencia', 30),
  ('San Martín de Porres', 'San Miguel', 45),   ('San Martín de Porres', 'Magdalena del Mar', 50),   ('San Martín de Porres', 'Pueblo Libre', 50),   ('San Martín de Porres', 'Callao', 35),   ('San Martín de Porres', 'Ate', 85),
  ('Independencia', 'Cercado de Lima', 55),   ('Independencia', 'Breña', 50),   ('Independencia', 'La Victoria', 65),   ('Independencia', 'Lince', 65),   ('Independencia', 'San Isidro', 75),
  ('Independencia', 'Miraflores', 85),   ('Independencia', 'San Borja', 80),   ('Independencia', 'Surquillo', 85),   ('Independencia', 'Barranco', 95),   ('Independencia', 'Surco', 90),
  ('Independencia', 'La Molina', 100),   ('Independencia', 'Chorrillos', 95),   ('Independencia', 'Los Olivos', 30),   ('Independencia', 'San Martín de Porres', 30),   ('Independencia', 'Independencia', 0),
  ('Independencia', 'San Miguel', 65),   ('Independencia', 'Magdalena del Mar', 60),   ('Independencia', 'Pueblo Libre', 55),   ('Independencia', 'Callao', 55),   ('Independencia', 'Ate', 90),
  ('San Miguel', 'Cercado de Lima', 50),   ('San Miguel', 'Breña', 40),   ('San Miguel', 'La Victoria', 60),   ('San Miguel', 'Lince', 50),   ('San Miguel', 'San Isidro', 40),
  ('San Miguel', 'Miraflores', 45),   ('San Miguel', 'San Borja', 55),   ('San Miguel', 'Surquillo', 50),   ('San Miguel', 'Barranco', 65),   ('San Miguel', 'Surco', 65),
  ('San Miguel', 'La Molina', 90),   ('San Miguel', 'Chorrillos', 70),   ('San Miguel', 'Los Olivos', 55),   ('San Miguel', 'San Martín de Porres', 45),   ('San Miguel', 'Independencia', 65),
  ('San Miguel', 'San Miguel', 0),   ('San Miguel', 'Magdalena del Mar', 15),   ('San Miguel', 'Pueblo Libre', 20),   ('San Miguel', 'Callao', 25),   ('San Miguel', 'Ate', 80),
  ('Magdalena del Mar', 'Cercado de Lima', 45),   ('Magdalena del Mar', 'Breña', 35),   ('Magdalena del Mar', 'La Victoria', 55),   ('Magdalena del Mar', 'Lince', 45),   ('Magdalena del Mar', 'San Isidro', 35),
  ('Magdalena del Mar', 'Miraflores', 40),   ('Magdalena del Mar', 'San Borja', 50),   ('Magdalena del Mar', 'Surquillo', 45),   ('Magdalena del Mar', 'Barranco', 60),   ('Magdalena del Mar', 'Surco', 60),
  ('Magdalena del Mar', 'La Molina', 85),   ('Magdalena del Mar', 'Chorrillos', 65),   ('Magdalena del Mar', 'Los Olivos', 60),   ('Magdalena del Mar', 'San Martín de Porres', 50),   ('Magdalena del Mar', 'Independencia', 60),
  ('Magdalena del Mar', 'San Miguel', 15),   ('Magdalena del Mar', 'Magdalena del Mar', 0),   ('Magdalena del Mar', 'Pueblo Libre', 15),   ('Magdalena del Mar', 'Callao', 35),   ('Magdalena del Mar', 'Ate', 80),
  ('Pueblo Libre', 'Cercado de Lima', 40),   ('Pueblo Libre', 'Breña', 30),   ('Pueblo Libre', 'La Victoria', 50),   ('Pueblo Libre', 'Lince', 40),   ('Pueblo Libre', 'San Isidro', 35),
  ('Pueblo Libre', 'Miraflores', 40),   ('Pueblo Libre', 'San Borja', 45),   ('Pueblo Libre', 'Surquillo', 45),   ('Pueblo Libre', 'Barranco', 60),   ('Pueblo Libre', 'Surco', 60),
  ('Pueblo Libre', 'La Molina', 85),   ('Pueblo Libre', 'Chorrillos', 65),   ('Pueblo Libre', 'Los Olivos', 60),   ('Pueblo Libre', 'San Martín de Porres', 50),   ('Pueblo Libre', 'Independencia', 55),
  ('Pueblo Libre', 'San Miguel', 20),   ('Pueblo Libre', 'Magdalena del Mar', 15),   ('Pueblo Libre', 'Pueblo Libre', 0),   ('Pueblo Libre', 'Callao', 40),   ('Pueblo Libre', 'Ate', 75),
  ('Callao', 'Cercado de Lima', 60),   ('Callao', 'Breña', 50),   ('Callao', 'La Victoria', 70),   ('Callao', 'Lince', 65),   ('Callao', 'San Isidro', 60),
  ('Callao', 'Miraflores', 70),   ('Callao', 'San Borja', 75),   ('Callao', 'Surquillo', 70),   ('Callao', 'Barranco', 85),   ('Callao', 'Surco', 85),
  ('Callao', 'La Molina', 105),   ('Callao', 'Chorrillos', 90),   ('Callao', 'Los Olivos', 45),   ('Callao', 'San Martín de Porres', 35),   ('Callao', 'Independencia', 55),
  ('Callao', 'San Miguel', 25),   ('Callao', 'Magdalena del Mar', 35),   ('Callao', 'Pueblo Libre', 40),   ('Callao', 'Callao', 0),   ('Callao', 'Ate', 95),
  ('Ate', 'Cercado de Lima', 65),   ('Ate', 'Breña', 70),   ('Ate', 'La Victoria', 50),   ('Ate', 'Lince', 60),   ('Ate', 'San Isidro', 70),
  ('Ate', 'Miraflores', 75),   ('Ate', 'San Borja', 60),   ('Ate', 'Surquillo', 70),   ('Ate', 'Barranco', 80),   ('Ate', 'Surco', 65),
  ('Ate', 'La Molina', 45),   ('Ate', 'Chorrillos', 85),   ('Ate', 'Los Olivos', 95),   ('Ate', 'San Martín de Porres', 85),   ('Ate', 'Independencia', 90),
  ('Ate', 'San Miguel', 80),   ('Ate', 'Magdalena del Mar', 80),   ('Ate', 'Pueblo Libre', 75),   ('Ate', 'Callao', 95),   ('Ate', 'Ate', 0);